project_id = "vdpvmxzcdjtjkiwylpuv"
[functions.track-email-open]
enabled = true
verify_jwt = true
import_map = "./functions/track-email-open/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/track-email-open/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/track-email-open/*.html" ]

[functions.resend-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/resend-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/resend-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/resend-webhook/*.html" ]

[functions.receive-email]
enabled = true
verify_jwt = false
import_map = "./functions/receive-email/deno.json"
entrypoint = "./functions/receive-email/index.ts"
